### ISSUE TITLE
Where is the data available?

### ISSUE THREAD

**Issue by rizvisaira** [parthpatwa/covid19-fake-news-dectection#1]
I can't seem to access the data. Is it open for everyone to use?

**Comment by shlokgilda** [comment]
I have the same question. Where is the dataset?

**Comment by walkermoskop** [comment]
Same question.

**Comment by shlokgilda** [comment]
Hi people. You'll have to apply for this competition. https://competitions.codalab.org/competitions/26655
Once they accept your registration request, you'll get access to the dataset.

**Comment by hritik5102** [comment]
@shlokgilda If get the dataset, can you please share it with us on the drive or something

**Comment by shlokgilda** [comment]
@hritik5102 I'm sorry, but I'm not allowed to do that. It's against the rules of the competition. Although, applying to the competition is super easy. You get the access within an hour.

**Comment by hritik5102** [comment]
Yeah, right ... I thought it would be a hectic process, but I got the access within 10 mins.

**Comment by kanakmi** [comment]
The dataset that we would get will be labeled or unlabeled?

**Comment by parthpatwa** [comment]
please apply to https://competitions.codalab.org/competitions/26655#participate to get the dataset 
the dataset is labelled. 

you are not allowed to reshare the dataset (on dive or any platform) with anyone except with immediate collaborators.
